---
title: "Ivory-Billed Woodpecker"
author: "Brianna Saylor"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
packages<-c("cowplot","dismo","leaflet","mapdata","OpenStreetMap","rasterVis","rdryad","rgbif","sf","tidyverse", "ggspatial", "geodata")
sapply(packages, library, character.only=T)
```

```{r woodpecker gbif data, echo=TRUE, message=FALSE, warning=FALSE}
pilo.dismo <- gbif("campephilus", species = "principalis", ext = c(-130, -70, 10, 50, 
                    geo = TRUE, download = TRUE, removeZeros = TRUE))
```

```{r simple woodpececker distribution, echo=TRUE, message=FALSE, warning=FALSE, fig.height=6, fig.width=7}
us <- map_data("state")

ggplot() +
  geom_polygon(data = us, aes(x=long, y = lat, group = group),
               fill = "white", color="black") +
  geom_point(data = pilo.dismo, aes(x=lon, y=lat), size = 2) + 
  xlab("Longitude") + ylab("Latitude") +
  coord_fixed(xlim = c(-97,-76), ylim = c(25,37)) +
  xlab("Longitude") + ylab("Latitude") + ggtitle("Historic Ivory-Billed Woodpecker Range") + 
  theme_bw() + theme(plot.title = element_text(hjust = 0.5)) + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_rect(fill = "deepskyblue2"))  +
  annotation_scale(location = "bl", width_hint = 0.3) +
  annotation_north_arrow(
    location = "bl",
    which_north = "true",
    pad_x = unit(0.3, "in"), pad_y = unit(0.3, "in"),
    style = north_arrow_fancy_orienteering(fill = c("black","black"), text_size = 0,))
```

```{r limit to us distribution, echo=TRUE, message=FALSE, warning=FALSE}
pilo.rgbif <- occ_data(scientificName = "Campephilus principalis",
                       hasCoordinate = TRUE,
                       decimalLongitude = "-97,-76", 
                       decimalLatitude = "25,37")
```

```{r pilo piar data, echo=TRUE, message=FALSE, warning=FALSE}
pilo.rgbif.df <- cbind.data.frame(pilo.rgbif$data$species,
                                  pilo.rgbif$data$decimalLatitude,
                                  pilo.rgbif$data$decimalLongitude,
                                  pilo.rgbif$data$basisOfRecord,
                                  pilo.rgbif$data$stateProvince,
                                  pilo.rgbif$data$year,
                                  pilo.rgbif$data$locality,
                                  pilo.rgbif$data$verbatimLocality)
colnames(pilo.rgbif.df) <- c("species","y","x", "BasisOfRecord", "state","year","location", "VerbatimLocation")
```

```{r species distribution, echo=TRUE, message=FALSE, warning=FALSE}
# bioclim <- getData(name = "worldclim", res = 2.5, var = "bio", path = "./")
# getData no long works

bioclim <- worldclim_global(var = "bio", res = 10, path = "./")
bioclim <- bioclim[[c(1, 3, 10, 11, 12, 16, 17)]] # select only the variable we are interested in
names(bioclim) <- c("Ann Mean Temp","Isothermality", "Mean Temp Warmest Qtr","Mean Temp Coldest Qtr",
                    "Annual Precip","Precip Wettest Qtr","Precip Driest Qtr")

bio.extent <- extent(x = c(
  min(pilo.rgbif.df$x),
  max(pilo.rgbif.df$x),
  min(pilo.rgbif.df$y),
  max(pilo.rgbif.df$y)))

bioclim.extent <- crop(x = bioclim, y = bio.extent)

bioclim_raster <- raster::stack(bioclim.extent) # convert SpatRaster to Raster so dismo can handle it

bioclim.model <- bioclim(x = bioclim_raster, p = cbind(pilo.rgbif.df$x,pilo.rgbif.df$y))
presence.model <- dismo::predict(object = bioclim.model, 
                                 x = bioclim_raster, 
                                 ext = bio.extent)
```

```{r species distribution maps, echo=TRUE, message=FALSE, warning=FALSE, fig.height=6, fig.width=10}
rasterVis::gplot(presence.model) + 
  geom_polygon(data = us, aes(x= long, y = lat, group = group),
               fill = "gray", color="black") +
  geom_raster(aes(fill=value)) +
  geom_polygon(data = us, aes(x= long, y = lat, group = group),
               fill = NA, color="black") +
  geom_point(data = pilo.rgbif.df, aes(x = x, y = y), size = 2, color = "black", alpha = 0.5) +
  scale_fill_gradientn(colours=c("brown","yellow","darkgreen"), "Probability") +
  coord_fixed(xlim = c(-97,-76), ylim = c(25,37)) +
  xlab("Longitude") + ylab("Latitude") + ggtitle("Probability of IBWO Occurrence") + 
  theme_bw() + theme(plot.title = element_text(hjust = 0.5)) + theme(legend.position = "right") +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_rect(fill = "deepskyblue2")) 
```

```{r leaflet species distribution, echo=TRUE, message=FALSE, warning=FALSE, fig.height=8, fig.width=10}
colors <- c("brown","yellow","darkgreen")

leaflet() %>% 
  addTiles() %>%
  addRasterImage(presence.model, colors = colors, opacity = 0.8) %>%
  addCircleMarkers(data = pilo.rgbif.df,
                   lng = ~x,
                   lat = ~y,
                   weight = 0.5,
                   color = "grey",
                   fillColor = "green",
                   fillOpacity = 0.7,
                   popup = ~paste0(
  "<b>Year:</b> ", ifelse(is.na(year), "NULL", year), "<br>",
  "<b>Basis of Record:</b> ", ifelse(is.na(BasisOfRecord), "NULL", BasisOfRecord), "<br>",
  "<b>Location:</b> ", ifelse(is.na(location), "NULL", location))) %>%
  addMiniMap(position = 'topright',
             width = 100, 
             height = 100,
             toggleDisplay = FALSE) %>%
  addScaleBar(position = "bottomright")
```